MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
  NUM_CLASSES: 10
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
  NUM_CLASSES: 10
DATASET_SOURCE:
  TYPE: "A2D2SCN"
  TRAIN: ("train",)
  A2D2SCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/a2d2_preprocess"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN_LABELED: ("train_labeled",)
  TRAIN_UNLABELED: ("train_unlabeled",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SRC_TRG_RATIO: 0.5
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS_SRC: [1.89090012, 2.0585112, 3.1970535, 3.1111633, 1., 2.93751704, 1.92053733,
                      1.47886874, 1.04654198, 1.78266561]  # A2D2
  CLASS_WEIGHTS_TRG: [1.44266267, 3.28192912, 2.89684809, 3.40990009, 1., 2.22021218,
                      1.44144653, 1.26582799, 1.03503295, 1.59859966]  # SemanticKITTI train_labeled
  XMUDA:
    lambda_xm_src: 0.1
    lambda_xm_trg: 0.01
VAL:
  BATCH_SIZE: 2
  PERIOD: 5000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda