MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 10
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 10
DATASET_SOURCE:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train_labeled",)
  SemanticKITTISCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.44266267, 3.28192912, 2.89684809, 3.40990009, 1., 2.22021218,
                  1.44144653, 1.26582799, 1.03503295, 1.59859966]  # SemanticKITTI train_labeled
VAL:
  BATCH_SIZE: 2
  PERIOD: 5000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda